repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=600']
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: [ --unsafe ]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix, --no-sort]

  - repo: local
    hooks:
    -   id: ruff
        name: ruff (local)
        entry: uv run ruff check --fix
        language: system
        types: [python]
    # -   id: mypy
    #     name: mypy (local)
    #     entry: uv run mypy
    #     language: system
    #     types: [python]
    #     args: []
